### ISSUE TITLE
How about other GAN@GTEx?

### ISSUE THREAD

**Issue by yezhengli-Mr9** [rvinas/GTEx-imputation#6]
Is it too time-consuming to compare with other GAN@GTEx work (they are on older version of GTEx anyway)?

Wang, Xiaoqian, Kamran Ghasedi Dizaji, and Heng Huang. ["Conditional generative adversarial network for gene expression inference](https://europepmc.org/article/med/30423066)." Bioinformatics 34.17 (2018): i603-i611.
Ghasedi Dizaji, Kamran, Xiaoqian Wang, and Heng Huang. ["Semi-supervised generative adversarial network for gene expression inference."](https://dl.acm.org/doi/abs/10.1145/3219819.3220114?casa_token=tArBqZaAloQAAAAA:3wrur_umoZ2OP77PRl7YxCOJpOJR34AUfq8hSRpD0T4YLJ_C9fzb6kXnc7Pox0mrPMaUlad8LXovyA) Proceedings of the 24th ACM SIGKDD International Conference on Knowledge Discovery & Data Mining. 2018.

**Comment by rvinas** [comment]
Good findings! Thanks for sharing, I will take a proper look at these papers soon.
While the methodology is slightly similar (e.g., GAN), the problem that we address here is different - our predictions are not based on landmark genes.

**Comment by yezhengli-Mr9** [comment]
> Good findings! Thanks for sharing, I will take a proper look at these papers soon.
> While the methodology is slightly similar (e.g., GAN), the problem that we address here is different - our predictions are not based on landmark genes.

I think they do not release codes. I am trying to find other codes to convince you of my that [second to last issue](https://github.com/rvinas/GAIN-GTEx/issues/5) makes sense -- I woke up 2 hours ago and keep looking for SIMPLE codes (for published work) that can convince you my that [second to last issue](https://github.com/rvinas/GAIN-GTEx/issues/5):
(1) Some GAN work/ codes for "missing imputation" actually analyze on compete data (for example, MNIST, CelebA, etc. that is they do not have input with intrinsic missing values) although they do pay attention to my [second to last issue](https://github.com/rvinas/GAIN-GTEx/issues/5).
(2) Some codes are not simple enough, or not talking about missing imputation.
(3) not peer-reviewed
(4) ...
